### PR TITLE
Remove deprecated parameter and update README for ImageName

### PR DESCRIPTION
**Pull request by biru-codeastromer**
Changes:
- Removed the deprecated `DEFAULT_NAME` constant (`sysdig_secure_images`) from `ImageScanningStep.java`, as it is no longer referenced since the deprecation of the legacy scanner.
- Updated the README to reflect that `ImageName` is a mandatory parameter and defaults to `null`.

This resolves:
- Issue 1: README stated incorrect default value for `ImageName`.
- Issue 2: Deprecated `DEFAULT_NAME` constant was still present in the codebase.

@tembleking i hope sir these solved it!

### CODE REVIEW

**Review by tembleking — APPROVED** [review]

**Comment by tembleking** [comment]
Thank you for the change @biru-codeastromer :)

**Comment by biru-codeastromer** [comment]
@tembleking you are welcome sir.

**Comment by S0obi** [comment]
@tembleking @biru-codeastromer this PR actually broke the README table (the extra new line added on line 123) : 
image.

I proposed #114 to fix this issue.

**Comment by biru-codeastromer** [comment]
@S0obi Thank you for pointing this out and taking the time to propose a fix! I didn’t notice the extra newline when raising the PR, so I appreciate your sharp eye for detail.

Let me know if there’s anything else I can assist with regarding this or similar issues moving forward.

**Pull request merged**
